version: '3.2'

services:
  node_exporter:
    image: prom/node-exporter:$NODE_EXPORTER_VERSION
    command:
      - '--path.rootfs=/host'
    pid: host
    ports:
      - $NODE_EXPORTER_PORTS
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
    container_name: node_exporter

  prometheus:
    image: prom/prometheus:$PROMETHEUS_VERSION
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - $PROMETHEUS_PORTS
    restart: unless-stopped
    container_name: prometheus

  memcached_exporter:
    image: prom/memcached-exporter:$MEMCACHED_VERSION
    container_name: memcached_exporter
    command: 
      - '--memcached.address=$MEMCACHED_ADDRESS'
    ports:
      - $MEMCACHED_EXPORTER_PORTS

  mysql_exporter:
    image: prom/mysqld-exporter:$MYSQLD_EXPORTER_VERSION
    container_name: mysql_exporter
    environment:
      DATA_SOURCE_NAME: '$DATA_SOURCE_NAME'
    ports:
      - $MYSQLD_EXPORTER_PORTS

  grafana:
    image: grafana/grafana:$GRAFANA_VERSION
    environment:
      GF_SECURITY_ADMIN_USER: $GF_SECURITY_ADMIN_USER
      GF_SECURITY_ADMIN_PASSWORD: $GF_SECURITY_ADMIN_PASSWORD
      GF_USERS_ALLOW_SIGN_UP: $GF_USERS_ALLOW_SIGN_UP
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - 3000:3000

volumes:
    prometheus_data: {}
    grafana_data: {}