version: '3.2'

services:
  prometheus:
    build:
      context: './.docker/'
    volumes:
      - ./.config/etc:/etc/prometheus/
      - ./.config/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus/data'
    ports:
      - 9090:9090
    restart: always
    networks:
      - promnet
    container_name: deucalion

networks:
  promnet: