version: '3.2'

services:
  prometheus:
    build:
      context: ./docker/
    volumes:
      - ./.config/:/etc/prometheus/
      - ./prometheus:/prometheus
    # command:
      # - '--config.file=/etc/prometheus/prometheus.yml'
    #   - '--storage.tsdb.path=/data'
    ports:
      - 9090:9090
    restart: always
    networks:
      - promnet
    container_name: deucalion_prom

networks:
  promnet: